export const ADD_NEW_TASK='ADD_NEW_TASK';
export const DELETE_FROM_BACKLOG='DELETE_FROM_BACKLOG';
export const MOVE_TO_IN_PROGRESS='MOVE_TO_IN_PROGRESS';
export const MOVE_TO_DONE='MOVE_TO_DONE';
export const DELETE_FROM_DONE='DELETE_FROM_DONE';